//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeramicaCarrillo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonos
    {
        public int IdAbono { get; set; }
        public double MontoAbono { get; set; }
        public System.DateTime FechaAbono { get; set; }
        public int IdFolio { get; set; }
    
        public virtual Folio Folio { get; set; }
    }
}
