//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productoss.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Anomalias = new HashSet<Anomalias>();
            this.Solicitudes = new HashSet<Solicitudes>();
            this.Folio = new HashSet<Folio>();
        }
    
        public int IdProductos { get; set; }
        [Required(ErrorMessage ="El campo {0} no puede estar vacío")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo {0} no puede estar vacío")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El campo {0} no puede estar vacío")]
        [DataType(DataType.Currency)]
        public Nullable<double> PrecioCompra { get; set; }
        [Required(ErrorMessage = "El campo {0} no puede estar vacío")]
        [DataType(DataType.Currency)]
        public Nullable<double> PrecioVenta { get; set; }
        [Required(ErrorMessage = "El campo {0} no puede estar vacío")]
        public Nullable<int> Unidades { get; set; }
        public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anomalias> Anomalias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Folio> Folio { get; set; }
    }
}
